# Generated by cucumber-sinatra. (2010-09-28 14:40:06 +0200)

require File.join(File.dirname(__FILE__), '..', '..', 'sna.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

SimpleNewsAggregation.set(:environment, :test)

Capybara.app = SimpleNewsAggregation

class SimpleNewsAggregationWorld
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end

World do
  SimpleNewsAggregationWorld.new
end
